//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura_Kayıt_Sistemi.WebService_ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService_.WebService_Soap")]
    public interface WebService_Soap {
        
        // CODEGEN: Generating message contract since element name programVersion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUpdate", ReplyAction="*")]
        Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse CheckUpdate(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse> CheckUpdateAsync(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLisance", ReplyAction="*")]
        Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse CheckLisance(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLisance", ReplyAction="*")]
        System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse> CheckLisanceAsync(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUpdate", Namespace="http://tempuri.org/", Order=0)]
        public Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequestBody Body;
        
        public CheckUpdateRequest() {
        }
        
        public CheckUpdateRequest(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string programVersion;
        
        public CheckUpdateRequestBody() {
        }
        
        public CheckUpdateRequestBody(string programVersion) {
            this.programVersion = programVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponseBody Body;
        
        public CheckUpdateResponse() {
        }
        
        public CheckUpdateResponse(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckUpdateResult;
        
        public CheckUpdateResponseBody() {
        }
        
        public CheckUpdateResponseBody(string CheckUpdateResult) {
            this.CheckUpdateResult = CheckUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLisanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLisance", Namespace="http://tempuri.org/", Order=0)]
        public Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequestBody Body;
        
        public CheckLisanceRequest() {
        }
        
        public CheckLisanceRequest(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLisanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string activator;
        
        public CheckLisanceRequestBody() {
        }
        
        public CheckLisanceRequestBody(string email, string key, string activator) {
            this.email = email;
            this.key = key;
            this.activator = activator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLisanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLisanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponseBody Body;
        
        public CheckLisanceResponse() {
        }
        
        public CheckLisanceResponse(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLisanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckLisanceResult;
        
        public CheckLisanceResponseBody() {
        }
        
        public CheckLisanceResponseBody(string CheckLisanceResult) {
            this.CheckLisanceResult = CheckLisanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_SoapChannel : Fatura_Kayıt_Sistemi.WebService_.WebService_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_SoapClient : System.ServiceModel.ClientBase<Fatura_Kayıt_Sistemi.WebService_.WebService_Soap>, Fatura_Kayıt_Sistemi.WebService_.WebService_Soap {
        
        public WebService_SoapClient() {
        }
        
        public WebService_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse Fatura_Kayıt_Sistemi.WebService_.WebService_Soap.CheckUpdate(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest request) {
            return base.Channel.CheckUpdate(request);
        }
        
        public string CheckUpdate(string programVersion) {
            Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest inValue = new Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest();
            inValue.Body = new Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequestBody();
            inValue.Body.programVersion = programVersion;
            Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse retVal = ((Fatura_Kayıt_Sistemi.WebService_.WebService_Soap)(this)).CheckUpdate(inValue);
            return retVal.Body.CheckUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse> Fatura_Kayıt_Sistemi.WebService_.WebService_Soap.CheckUpdateAsync(Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest request) {
            return base.Channel.CheckUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckUpdateResponse> CheckUpdateAsync(string programVersion) {
            Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest inValue = new Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequest();
            inValue.Body = new Fatura_Kayıt_Sistemi.WebService_.CheckUpdateRequestBody();
            inValue.Body.programVersion = programVersion;
            return ((Fatura_Kayıt_Sistemi.WebService_.WebService_Soap)(this)).CheckUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse Fatura_Kayıt_Sistemi.WebService_.WebService_Soap.CheckLisance(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest request) {
            return base.Channel.CheckLisance(request);
        }
        
        public string CheckLisance(string email, string key, string activator) {
            Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest inValue = new Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest();
            inValue.Body = new Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequestBody();
            inValue.Body.email = email;
            inValue.Body.key = key;
            inValue.Body.activator = activator;
            Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse retVal = ((Fatura_Kayıt_Sistemi.WebService_.WebService_Soap)(this)).CheckLisance(inValue);
            return retVal.Body.CheckLisanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse> Fatura_Kayıt_Sistemi.WebService_.WebService_Soap.CheckLisanceAsync(Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest request) {
            return base.Channel.CheckLisanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fatura_Kayıt_Sistemi.WebService_.CheckLisanceResponse> CheckLisanceAsync(string email, string key, string activator) {
            Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest inValue = new Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequest();
            inValue.Body = new Fatura_Kayıt_Sistemi.WebService_.CheckLisanceRequestBody();
            inValue.Body.email = email;
            inValue.Body.key = key;
            inValue.Body.activator = activator;
            return ((Fatura_Kayıt_Sistemi.WebService_.WebService_Soap)(this)).CheckLisanceAsync(inValue);
        }
    }
}
